INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (9512, ' Acme Corporation', ' 123 Main St', ' 205-288-8591', ' info@acme-corp.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (8642, ' Xerox Inc.', ' 456 High St', ' 505-398-8414', ' info@xrx.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (3579, ' RedPark Ltd.', ' 789 Park Ave', ' 604-683-2555', ' info@redpark.ca');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (7890, ' Samsung', ' 456 Seoul St', ' 909-763-4442', ' support@samsung.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (7671, ' LG Electronics', ' 789 Busan St', ' 668-286-5378', ' support@lge.kr');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (9876, ' Toshiba', ' 246 Osaka St', ' 90-6378-0835', ' support@toshiba.co.jp');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (3456, ' Panasonic', ' 246 Osaka St', ' 443-887-9967', ' support@panasonic.co.jp');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (8765, ' Philips', ' 789 Amsterdam St', ' 61-483-898-670', ' support@philips.au');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (1357, ' Sharp', ' 123 Tokyo St', ' 80-4745-3107', ' support@sharp.co.jp');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (9144, ' Fujitsu', ' 456 Tokyo St', ' 03-3556-7890', ' support@fujitsu.co.jp');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (8655, ' Dell', ' 246 Austin St', ' 505-351-3181', ' support@dell.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (3592, ' IBM', ' 456 New York St', ' 201-335-9423', ' support@ibm.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (7084, ' Acer', ' 135 Taipei St', ' 905-926-031', ' support@acer.tw');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (2345, ' MSI', ' 789 Mofan St', ' 943-299-465', ' support@msi.tw');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (6954, ' Apple', ' 246 Cupertino St', ' 202-918-2132', ' support@apple.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (9794, ' Amazon', ' 246 Seattle St', ' 555-343-8950', ' support@amazon.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (8692, ' Microsoft', ' 123 Redmond St', ' 505-549-0420', ' support@microsoft.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (7807, ' Intel', ' 2200 Mission College Blvd', ' 408-646-7611', ' support@intel.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (8672, ' AMD', ' 246 Santa Clara St', ' 312-866-2043', ' support@amd.com');
INSERT INTO Suppliers (SupplierID, SupplierName, Address, Phone, Email) VALUES (4567, ' Qualcomm', ' 456 San Diego St', ' 44-7700-087231', ' info@qualcomm.co.uk');
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3374, ' Laptop', ' MacBook Pro', 1799.9, 30, 'A', 9876);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3034, ' Telephone', ' Cordless Phone', 299.99, 40, 'A', 3456);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3034, ' Telephone', ' Home telephone', 99.9, 25, 'A', 8765);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1234, ' TV', ' Plate TV', 799.9, 20, 'C', 9144);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1234, ' TV', ' Plate TV', 1499.99, 5, 'A', 7671);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (2591, ' Camera', ' Instant Camera', 179.5, 30, 'C', 8642);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1516, ' Mouse', ' Wireless Mouse', 99.5, 30, 'A', 3579);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3034, ' Telephone', ' Home Telephone', 169.99, 15, 'A', 8692);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (2591, ' Camera', ' Digital Camera', 499.9, 10, 'B', 9512);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3034, ' Telephone', ' Home Telephone', 59.5, 20, 'A', 8655);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (2591, ' Camera', ' Digital Camera', 449.4, 50, 'A', 3592);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1234, ' TV', ' Plate TV', 699.7, 5, 'B', 7084);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1516, ' Mouse', ' Wireless Mouse', 69.9, 25, 'C', 2345);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3374, ' Laptop', ' Laptop', 1399.2, 10, 'B', 1357);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3374, ' Laptop', ' Refurbished Laptop', 1099.1, 20, 'A', 6954);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1516, ' Mouse', ' Wireless Mouse', 49.4, 50, 'B', 9794);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1516, ' Mouse', ' Wireless Mouse', 69.5, 20, 'A', 7807);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (1234, ' TV', ' Plate TV', 599.3, 5, 'B', 8672);
INSERT INTO Product (ProductID, ProductName, Description, Price, Quantity, Status, SupplierID) VALUES (3374, ' Laptop', ' Laptop', 1369.9, 15, 'A', 4567);